services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jeevan_setu_backend
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env

