services:
  backend:
    image: ${DOCKER_IMAGE:-jeevansetu-backend:latest}
    build:
      context: .
    container_name: jeevansetu-backend
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      ORIGIN: ${ORIGIN:-https://www.jeevansetu.org}